name: todo_rest_api
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  darto: ^0.0.35
  dartonic: ^0.0.14
  zard: ^0.0.25

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
